Repository openshift/ibm-vpc-block-csi-driver-operator, pull requests merged in 2021-12, with the labels that each got.

#7 annotations removed
  assets/controller_sa.yaml
  assets/node_sa.yaml
  assets/rbac/attacher_role.yaml
  assets/rbac/attacher_rolebinding.yaml
  assets/rbac/provisioner_binding.yaml
  assets/rbac/provisioner_role.yaml
  assets/rbac/registrar_binding.yaml
  assets/rbac/registrar_role.yaml
  assets/storageclass/vpc-block-10iopsTier-StorageClass.yaml
  assets/storageclass/vpc-block-5iopsTier-StorageClass.yaml
  assets/storageclass/vpc-block-custom-StorageClass.yaml
Labels: approved, lgtm, ok-to-test

#8 Bug 2028484: CSI driver's livenessprobe does not respect operator's loglevel
  assets/controller.yaml
  assets/node.yaml
Labels: approved, lgtm

#12 Bug 2033711: IBM VPC operator needs e2e csi tests for ibmcloud
  Dockerfile.test
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#11 Bug 2033111: IBM VPC operator library bump removed global CLI args
  Dockerfile
  assets/storageclass/vpc-block-10iopsTier-StorageClass.yaml
  assets/storageclass/vpc-block-5iopsTier-StorageClass.yaml
  assets/storageclass/vpc-block-custom-StorageClass.yaml
  cmd/ibm-vpc-block-csi-driver-operator/main.go
  go.mod
  pkg/controller/secret/secretsync.go
  pkg/controller/secret/secretsync_test.go
  pkg/operator/starter.go
  vendor/k8s.io/component-base/cli/OWNERS
  vendor/k8s.io/component-base/cli/run.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#13 Bug 2033711: IBM VPC operator needs e2e csi tests for ibmcloud
  test/e2e/manifest.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
