Repository openshift/ibm-vpc-block-csi-driver-operator, pull requests merged in 2023-11, with the labels that each got.

#87 OCPBUGS-22924: Removing unncessary imagePullSecrets
  assets/controller_sa.yaml
  assets/node_sa.yaml
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#89 STOR-1485: Support for endpoint override from config
  README.md
  assets/node.yaml
  assets/rbac/label_updater_role.yaml
  assets/rbac/node_label_updater_binding.yaml
  manifests/08_deployment.yaml
  pkg/controller/secret/secretsync.go
  pkg/controller/secret/secretsync_test.go
  pkg/operator/starter.go
Labels: approved, qe-approved, docs-approved, px-approved, lgtm, ok-to-test, jira/valid-reference, acknowledge-critical-fixes-only

#93 STOR-1487: Provide BYOK encryption support for OpenShift on IBM Cloud VPC
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/storageclasshook.go
  pkg/operator/storageclasshook_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-Default.crd.yaml
  vendor/github.com/openshift/api/machine/v1/0000_10_controlplanemachineset-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.clustercsidriver.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, qe-approved, docs-approved, px-approved, lgtm, jira/valid-reference
